/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StructuredOutputControllerFindAllRequestSortOrder = "ASC" | "DESC";
export const StructuredOutputControllerFindAllRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
