/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../../index";

/**
 * @example
 *     {
 *         name: "Q2 Sales Campaign",
 *         phoneNumberId: "phoneNumberId",
 *         schedulePlan: {
 *             earliestAt: "2024-01-15T09:30:00Z"
 *         },
 *         customers: [{}]
 *     }
 */
export interface CreateCampaignDto {
    /** This is the name of the campaign. This is just for your own reference. */
    name: string;
    /** This is the assistant ID that will be used for the campaign calls. Note: Either assistantId or workflowId can be used, but not both. */
    assistantId?: string;
    /** This is the workflow ID that will be used for the campaign calls. Note: Either assistantId or workflowId can be used, but not both. */
    workflowId?: string;
    /** This is the phone number ID that will be used for the campaign calls. */
    phoneNumberId: string;
    /** This is the schedule plan for the campaign. */
    schedulePlan: Vapi.SchedulePlan;
    /** These are the customers that will be called in the campaign. */
    customers: Vapi.CreateCustomerDto[];
}
