/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type BlocksGetResponse =
    | Vapi.BlocksGetResponse.Conversation
    | Vapi.BlocksGetResponse.ToolCall
    | Vapi.BlocksGetResponse.Workflow;

export declare namespace BlocksGetResponse {
    interface Conversation extends Vapi.ConversationBlock {
        type: "conversation";
    }

    interface ToolCall extends Vapi.ToolCallBlock {
        type: "tool-call";
    }

    interface Workflow extends Vapi.WorkflowBlock {
        type: "workflow";
    }
}
