/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type BlocksListResponseItem =
    | Vapi.BlocksListResponseItem.Conversation
    | Vapi.BlocksListResponseItem.ToolCall
    | Vapi.BlocksListResponseItem.Workflow;

export declare namespace BlocksListResponseItem {
    interface Conversation extends Vapi.ConversationBlock {
        type: "conversation";
    }

    interface ToolCall extends Vapi.ToolCallBlock {
        type: "tool-call";
    }

    interface Workflow extends Vapi.WorkflowBlock {
        type: "workflow";
    }
}
