/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ApiRequestToolMethod = "POST" | "GET";
export const ApiRequestToolMethod = {
    Post: "POST",
    Get: "GET",
} as const;
