/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssistantUserEditableBackgroundSoundZero = "off" | "office";
export const AssistantUserEditableBackgroundSoundZero = {
    Off: "off",
    Office: "office",
} as const;
