/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type AssistantUserEditableHooksItem =
    | Vapi.AssistantHookCallEnding
    | Vapi.AssistantHookAssistantSpeechInterrupted
    | Vapi.AssistantHookCustomerSpeechInterrupted;
