/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the provider-specific ID that will be used.
 */
export type AzureVoiceVoiceId = "andrew" | "brian" | "emma" | string;
