/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type BlockStartMessageConditionsItem =
    | Vapi.BlockStartMessageConditionsItem.ModelBased
    | Vapi.BlockStartMessageConditionsItem.RuleBased;

export declare namespace BlockStartMessageConditionsItem {
    interface ModelBased extends Vapi.ModelBasedCondition {
        type: "model-based";
    }

    interface RuleBased extends Vapi.RuleBasedCondition {
        type: "rule-based";
    }
}
