/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type BlockCompleteMessageConditionsItem =
    | Vapi.BlockCompleteMessageConditionsItem.ModelBased
    | Vapi.BlockCompleteMessageConditionsItem.RuleBased;

export declare namespace BlockCompleteMessageConditionsItem {
    interface ModelBased extends Vapi.ModelBasedCondition {
        type: "model-based";
    }

    interface RuleBased extends Vapi.RuleBasedCondition {
        type: "rule-based";
    }
}
