/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type CallCostsItem =
    | Vapi.CallCostsItem.Transport
    | Vapi.CallCostsItem.Transcriber
    | Vapi.CallCostsItem.Model
    | Vapi.CallCostsItem.Voice
    | Vapi.CallCostsItem.Vapi
    | Vapi.CallCostsItem.Analysis;

export declare namespace CallCostsItem {
    interface Transport extends Vapi.TransportCost {
        type: "transport";
    }

    interface Transcriber extends Vapi.TranscriberCost {
        type: "transcriber";
    }

    interface Model extends Vapi.ModelCost {
        type: "model";
    }

    interface Voice extends Vapi.VoiceCost {
        type: "voice";
    }

    interface Vapi extends Vapi.VapiCost {
        type: "vapi";
    }

    interface Analysis extends Vapi.AnalysisCost {
        type: "analysis";
    }
}
