/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface CallHookCustomerSpeechInterrupted {
    /** This is the event that triggers this hook */
    on: "customer.speech.interrupted";
    /** This is the set of actions to perform when the hook triggers */
    do: CallHookCustomerSpeechInterrupted.Do.Item[];
}

export namespace CallHookCustomerSpeechInterrupted {
    export type Do = Do.Item[];

    export namespace Do {
        export type Item = Vapi.SayHookAction | Vapi.ToolCallHookAction;
    }
}
