/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CallLogPrivileged {
    /** This is the unique identifier for the call. */
    callId: string;
    /** This is the unique identifier for the org that this call log belongs to. */
    orgId: string;
    /** This is the log message associated with the call. */
    log: string;
    /** This is the level of the log message. */
    level: CallLogPrivileged.Level;
    /** This is the ISO 8601 date-time string of when the log was created. */
    time: string;
}

export namespace CallLogPrivileged {
    /**
     * This is the level of the log message.
     */
    export type Level = "INFO" | "LOG" | "WARN" | "ERROR" | "CHECKPOINT";
    export const Level = {
        Info: "INFO",
        Log: "LOG",
        Warn: "WARN",
        Error: "ERROR",
        Checkpoint: "CHECKPOINT",
    } as const;
}
