/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * Chat input as a string or an array of messages. When using message array, each message requires a role and content.
 */
export type ChatInput = string | Vapi.ChatInputItem[];
