/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ChatPaginatedResponse {
    results: Vapi.Chat[];
    metadata: Vapi.PaginationMeta;
}
