/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientMessageLanguageChanged {
    /** This is the language the transcriber is switched to. */
    language: string;
}
