/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientInboundMessageSay {
    /** This is the content to say. */
    content?: string;
    /** This is the flag to end call after content is spoken. */
    endCallAfterSpoken?: boolean;
}
