/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientMessageToolCallsResult {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: Vapi.ClientMessageToolCallsResultPhoneNumber;
    /** This is the type of the message. "tool-calls-result" is sent to forward the result of a tool call to the client. */
    type: "tool-calls-result";
    /** This is the timestamp of the message. */
    timestamp?: number;
    /** This is the call that the message is associated with. */
    call?: Vapi.Call;
    /** This is the customer that the message is associated with. */
    customer?: Vapi.CreateCustomerDto;
    /** This is the assistant that the message is associated with. */
    assistant?: Vapi.CreateAssistantDto;
    /** This is the result of the tool call. */
    toolCallResult: Record<string, unknown>;
}
