/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientMessageToolCallsResult {
    /** This is the result of the tool call. */
    toolCallResult: Record<string, unknown>;
}
