/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientMessageSpeechUpdate {
    /** This is the status of the speech update. */
    status: Vapi.ClientMessageSpeechUpdateStatus;
    /** This is the role which the speech update is for. */
    role: Vapi.ClientMessageSpeechUpdateRole;
}
