/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the phone number that the message is associated with.
 */
export type ClientMessageTranscriptPhoneNumber = unknown | Vapi.CreateTwilioPhoneNumberDto;
