/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Condition {
    /** This is the operator you want to use to compare the parameter and value. */
    operator: Condition.Operator;
    /** This is the name of the parameter that you want to check. */
    param: string;
    /** This is the value you want to compare against the parameter. */
    value: string;
}

export namespace Condition {
    /**
     * This is the operator you want to use to compare the parameter and value.
     */
    export type Operator = "eq" | "neq" | "gt" | "gte" | "lt" | "lte";
    export const Operator = {
        Eq: "eq",
        Neq: "neq",
        Gt: "gt",
        Gte: "gte",
        Lt: "lt",
        Lte: "lte",
    } as const;
}
