/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface Conversation {
    type: "conversation";
    /** This is the model for the Conversation Task. */
    model?: Vapi.ConversationModel;
    /** These are the options for the assistant's transcriber. */
    transcriber?: Vapi.ConversationTranscriber;
    /** These are the options for the assistant's voice. */
    voice?: Vapi.ConversationVoice;
    prompt?: string;
    globalNodePlan?: Vapi.GlobalNodePlan;
    name: string;
    /** This is whether or not the node is the start of the workflow. */
    isStart?: boolean;
    /** This is for metadata you want to store on the task. */
    metadata?: Record<string, unknown>;
}
