/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the model for the Conversation Task.
 */
export type ConversationModel = Vapi.WorkflowOpenAiModel | Vapi.WorkflowAnthropicModel;
