/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the voice for the node.
 *
 * This overrides `workflow.voice`.
 */
export type ConversationNodeVoice =
    | Vapi.AzureVoice
    | Vapi.CartesiaVoice
    | Vapi.CustomVoice
    | Vapi.DeepgramVoice
    | Vapi.ElevenLabsVoice
    | Vapi.HumeVoice
    | Vapi.LmntVoice
    | Vapi.NeuphonicVoice
    | Vapi.OpenAiVoice
    | Vapi.PlayHtVoice
    | Vapi.RimeAiVoice
    | Vapi.SmallestAiVoice
    | Vapi.TavusVoice
    | Vapi.VapiVoice
    | Vapi.SesameVoice;
