/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type CreateFunctionToolDtoMessagesItem =
    | Vapi.CreateFunctionToolDtoMessagesItem.RequestStart
    | Vapi.CreateFunctionToolDtoMessagesItem.RequestComplete
    | Vapi.CreateFunctionToolDtoMessagesItem.RequestFailed
    | Vapi.CreateFunctionToolDtoMessagesItem.RequestResponseDelayed;

export declare namespace CreateFunctionToolDtoMessagesItem {
    interface RequestStart extends Vapi.ToolMessageStart {
        type: "request-start";
    }

    interface RequestComplete extends Vapi.ToolMessageComplete {
        type: "request-complete";
    }

    interface RequestFailed extends Vapi.ToolMessageFailed {
        type: "request-failed";
    }

    interface RequestResponseDelayed extends Vapi.ToolMessageDelayed {
        type: "request-response-delayed";
    }
}
