/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CreateSupabaseCredentialDto {
    /** This is for supabase storage. */
    provider: "supabase";
    bucketPlan?: Vapi.SupabaseBucketPlan;
    /** This is the name of credential. This is just for your reference. */
    name?: string;
}
