/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateApiRequestToolDtoMethod = "POST" | "GET";
export const CreateApiRequestToolDtoMethod = {
    Post: "POST",
    Get: "GET",
} as const;
