/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the authentication plan. Supports OAuth2 RFC 6749 and HMAC signing.
 */
export type CreateWebhookCredentialDtoAuthenticationPlan = Vapi.OAuth2AuthenticationPlan | Vapi.HmacAuthenticationPlan;
