/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type CreateConversationBlockDtoMessagesItem =
    | Vapi.CreateConversationBlockDtoMessagesItem.BlockStart
    | Vapi.CreateConversationBlockDtoMessagesItem.BlockComplete;

export declare namespace CreateConversationBlockDtoMessagesItem {
    interface BlockStart extends Vapi.BlockStartMessage {
        type: "block-start";
    }

    interface BlockComplete extends Vapi.BlockCompleteMessage {
        type: "block-complete";
    }
}
