/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface CreateToolTemplateDto {
    details?: CreateToolTemplateDto.Details;
    providerDetails?: CreateToolTemplateDto.ProviderDetails;
    metadata?: Vapi.ToolTemplateMetadata;
    visibility?: CreateToolTemplateDto.Visibility;
    type: "tool";
    /** The name of the template. This is just for your own reference. */
    name?: string;
    provider?: CreateToolTemplateDto.Provider;
}

export namespace CreateToolTemplateDto {
    export type Details =
        | Vapi.CreateApiRequestToolDto
        | Vapi.CreateBashToolDto
        | Vapi.CreateComputerToolDto
        | Vapi.CreateDtmfToolDto
        | Vapi.CreateEndCallToolDto
        | Vapi.CreateFunctionToolDto
        | Vapi.CreateGoHighLevelCalendarAvailabilityToolDto
        | Vapi.CreateGoHighLevelCalendarEventCreateToolDto
        | Vapi.CreateGoHighLevelContactCreateToolDto
        | Vapi.CreateGoHighLevelContactGetToolDto
        | Vapi.CreateGoogleCalendarCheckAvailabilityToolDto
        | Vapi.CreateGoogleCalendarCreateEventToolDto
        | Vapi.CreateGoogleSheetsRowAppendToolDto
        | Vapi.CreateMcpToolDto
        | Vapi.CreateQueryToolDto
        | Vapi.CreateSlackSendMessageToolDto
        | Vapi.CreateSmsToolDto
        | Vapi.CreateTextEditorToolDto
        | Vapi.CreateTransferCallToolDto;
    export type ProviderDetails =
        | Vapi.MakeToolProviderDetails
        | Vapi.GhlToolProviderDetails
        | Vapi.FunctionToolProviderDetails
        | Vapi.GoogleCalendarCreateEventToolProviderDetails
        | Vapi.GoogleSheetsRowAppendToolProviderDetails
        | Vapi.GoHighLevelCalendarAvailabilityToolProviderDetails
        | Vapi.GoHighLevelCalendarEventCreateToolProviderDetails
        | Vapi.GoHighLevelContactCreateToolProviderDetails
        | Vapi.GoHighLevelContactGetToolProviderDetails;
    export type Visibility = "public" | "private";
    export const Visibility = {
        Public: "public",
        Private: "private",
    } as const;
    export type Provider = "make" | "gohighlevel" | "function";
    export const Provider = {
        Make: "make",
        Gohighlevel: "gohighlevel",
        Function: "function",
    } as const;
}
