/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ElevenLabsPronunciationDictionary {
    /** The ID of the pronunciation dictionary */
    pronunciationDictionaryId: string;
    /** The name of the pronunciation dictionary */
    dictionaryName: string;
    /** The user ID of the creator */
    createdBy: string;
    /** The creation time in Unix timestamp */
    creationTimeUnix: number;
    /** The version ID of the pronunciation dictionary */
    versionId: string;
    /** The number of rules in this version */
    versionRulesNum: number;
    /** The permission level on this resource */
    permissionOnResource?: ElevenLabsPronunciationDictionary.PermissionOnResource;
    /** The description of the pronunciation dictionary */
    description?: string;
}

export namespace ElevenLabsPronunciationDictionary {
    /**
     * The permission level on this resource
     */
    export type PermissionOnResource = "admin" | "editor" | "viewer";
    export const PermissionOnResource = {
        Admin: "admin",
        Editor: "editor",
        Viewer: "viewer",
    } as const;
}
