/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EvalModelListOptions {
    /** This is the provider of the model. */
    provider: EvalModelListOptions.Provider;
}

export namespace EvalModelListOptions {
    /**
     * This is the provider of the model.
     */
    export type Provider = "openai" | "anthropic" | "google" | "groq" | "custom-llm";
    export const Provider = {
        Openai: "openai",
        Anthropic: "anthropic",
        Google: "google",
        Groq: "groq",
        CustomLlm: "custom-llm",
    } as const;
}
