/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Playht voice model/engine to use.
 */
export type FallbackPlayHtVoiceModel = "PlayHT2.0" | "PlayHT2.0-turbo" | "Play3.0-mini";

export const FallbackPlayHtVoiceModel = {
    PlayHt20: "PlayHT2.0",
    PlayHt20Turbo: "PlayHT2.0-turbo",
    Play30Mini: "Play3.0-mini",
} as const;
