/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface FallbackDeepgramVoice {
    /** This is the voice provider that will be used. */
    provider: "deepgram";
    /** This is the provider-specific ID that will be used. */
    voiceId: Vapi.FallbackDeepgramVoiceId;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan;
}
