/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface FallbackMinimaxVoice {
    /** This is the flag to toggle voice caching for the assistant. */
    cachingEnabled?: boolean;
    /** This is the voice provider that will be used. */
    provider: "minimax";
    /** This is the provider-specific ID that will be used. Use a voice from MINIMAX_PREDEFINED_VOICES or a custom cloned voice ID. */
    voiceId: string;
    /**
     * This is the model that will be used. Options are 'speech-02-hd' and 'speech-02-turbo'.
     * speech-02-hd is optimized for high-fidelity applications like voiceovers and audiobooks.
     * speech-02-turbo is designed for real-time applications with low latency.
     *
     * @default "speech-02-turbo"
     */
    model?: FallbackMinimaxVoice.Model;
    /**
     * The emotion to use for the voice. If not provided, will use auto-detect mode.
     * Options include: 'happy', 'sad', 'angry', 'fearful', 'surprised', 'disgusted', 'neutral'
     */
    emotion?: string;
    /**
     * Voice pitch adjustment. Range from -12 to 12 semitones.
     * @default 0
     */
    pitch?: number;
    /**
     * Voice speed adjustment. Range from 0.5 to 2.0.
     * @default 1.0
     */
    speed?: number;
    /**
     * Voice volume adjustment. Range from 0.5 to 2.0.
     * @default 1.0
     */
    volume?: number;
    /** The region for Minimax API. Defaults to "worldwide". */
    region?: FallbackMinimaxVoice.Region;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan;
}

export namespace FallbackMinimaxVoice {
    /**
     * This is the model that will be used. Options are 'speech-02-hd' and 'speech-02-turbo'.
     * speech-02-hd is optimized for high-fidelity applications like voiceovers and audiobooks.
     * speech-02-turbo is designed for real-time applications with low latency.
     *
     * @default "speech-02-turbo"
     */
    export type Model = "speech-02-hd" | "speech-02-turbo";
    export const Model = {
        Speech02Hd: "speech-02-hd",
        Speech02Turbo: "speech-02-turbo",
    } as const;
    /**
     * The region for Minimax API. Defaults to "worldwide".
     */
    export type Region = "worldwide" | "china";
    export const Region = {
        Worldwide: "worldwide",
        China: "china",
    } as const;
}
