/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface FallbackCartesiaVoice {
    /** This is the flag to toggle voice caching for the assistant. */
    cachingEnabled?: boolean;
    /** This is the voice provider that will be used. */
    provider: "cartesia";
    /** The ID of the particular voice you want to use. */
    voiceId: string;
    /** This is the model that will be used. This is optional and will default to the correct model for the voiceId. */
    model?: FallbackCartesiaVoice.Model;
    /** This is the language that will be used. This is optional and will default to the correct language for the voiceId. */
    language?: FallbackCartesiaVoice.Language;
    /** Experimental controls for Cartesia voice generation */
    experimentalControls?: Vapi.CartesiaExperimentalControls;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan;
}

export namespace FallbackCartesiaVoice {
    /**
     * This is the model that will be used. This is optional and will default to the correct model for the voiceId.
     */
    export type Model = "sonic-2" | "sonic-english" | "sonic-multilingual" | "sonic-preview" | "sonic";
    export const Model = {
        Sonic2: "sonic-2",
        SonicEnglish: "sonic-english",
        SonicMultilingual: "sonic-multilingual",
        SonicPreview: "sonic-preview",
        Sonic: "sonic",
    } as const;
    /**
     * This is the language that will be used. This is optional and will default to the correct language for the voiceId.
     */
    export type Language =
        | "en"
        | "de"
        | "es"
        | "fr"
        | "ja"
        | "pt"
        | "zh"
        | "hi"
        | "it"
        | "ko"
        | "nl"
        | "pl"
        | "ru"
        | "sv"
        | "tr";
    export const Language = {
        En: "en",
        De: "de",
        Es: "es",
        Fr: "fr",
        Ja: "ja",
        Pt: "pt",
        Zh: "zh",
        Hi: "hi",
        It: "it",
        Ko: "ko",
        Nl: "nl",
        Pl: "pl",
        Ru: "ru",
        Sv: "sv",
        Tr: "tr",
    } as const;
}
