/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FallbackOpenAiTranscriber {
    /** This is the transcription provider that will be used. */
    provider: "openai";
    /** This is the model that will be used for the transcription. */
    model: FallbackOpenAiTranscriber.Model;
    /** This is the language that will be set for the transcription. */
    language?: FallbackOpenAiTranscriber.Language;
}

export namespace FallbackOpenAiTranscriber {
    /**
     * This is the model that will be used for the transcription.
     */
    export type Model = "gpt-4o-transcribe" | "gpt-4o-mini-transcribe";
    export const Model = {
        Gpt4OTranscribe: "gpt-4o-transcribe",
        Gpt4OMiniTranscribe: "gpt-4o-mini-transcribe",
    } as const;
    /**
     * This is the language that will be set for the transcription.
     */
    export type Language =
        | "af"
        | "ar"
        | "hy"
        | "az"
        | "be"
        | "bs"
        | "bg"
        | "ca"
        | "zh"
        | "hr"
        | "cs"
        | "da"
        | "nl"
        | "en"
        | "et"
        | "fi"
        | "fr"
        | "gl"
        | "de"
        | "el"
        | "he"
        | "hi"
        | "hu"
        | "is"
        | "id"
        | "it"
        | "ja"
        | "kn"
        | "kk"
        | "ko"
        | "lv"
        | "lt"
        | "mk"
        | "ms"
        | "mr"
        | "mi"
        | "ne"
        | "no"
        | "fa"
        | "pl"
        | "pt"
        | "ro"
        | "ru"
        | "sr"
        | "sk"
        | "sl"
        | "es"
        | "sw"
        | "sv"
        | "tl"
        | "ta"
        | "th"
        | "tr"
        | "uk"
        | "ur"
        | "vi"
        | "cy";
    export const Language = {
        Af: "af",
        Ar: "ar",
        Hy: "hy",
        Az: "az",
        Be: "be",
        Bs: "bs",
        Bg: "bg",
        Ca: "ca",
        Zh: "zh",
        Hr: "hr",
        Cs: "cs",
        Da: "da",
        Nl: "nl",
        En: "en",
        Et: "et",
        Fi: "fi",
        Fr: "fr",
        Gl: "gl",
        De: "de",
        El: "el",
        He: "he",
        Hi: "hi",
        Hu: "hu",
        Is: "is",
        Id: "id",
        It: "it",
        Ja: "ja",
        Kn: "kn",
        Kk: "kk",
        Ko: "ko",
        Lv: "lv",
        Lt: "lt",
        Mk: "mk",
        Ms: "ms",
        Mr: "mr",
        Mi: "mi",
        Ne: "ne",
        No: "no",
        Fa: "fa",
        Pl: "pl",
        Pt: "pt",
        Ro: "ro",
        Ru: "ru",
        Sr: "sr",
        Sk: "sk",
        Sl: "sl",
        Es: "es",
        Sw: "sw",
        Sv: "sv",
        Tl: "tl",
        Ta: "ta",
        Th: "th",
        Tr: "tr",
        Uk: "uk",
        Ur: "ur",
        Vi: "vi",
        Cy: "cy",
    } as const;
}
