/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FallbackGladiaTranscriberModel = "fast" | "accurate" | "solaria-1";
export const FallbackGladiaTranscriberModel = {
    Fast: "fast",
    Accurate: "accurate",
    Solaria1: "solaria-1",
} as const;
