/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface FallbackVapiVoice {
    /** This is the flag to toggle voice caching for the assistant. */
    cachingEnabled?: boolean;
    /** This is the voice provider that will be used. */
    provider: "vapi";
    /** The voices provided by Vapi */
    voiceId: FallbackVapiVoice.VoiceId;
    /**
     * This is the speed multiplier that will be used.
     *
     * @default 1
     */
    speed?: number;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan;
}

export namespace FallbackVapiVoice {
    /**
     * The voices provided by Vapi
     */
    export type VoiceId =
        | "Elliot"
        | "Kylie"
        | "Rohan"
        | "Lily"
        | "Savannah"
        | "Hana"
        | "Neha"
        | "Cole"
        | "Harry"
        | "Paige"
        | "Spencer";
    export const VoiceId = {
        Elliot: "Elliot",
        Kylie: "Kylie",
        Rohan: "Rohan",
        Lily: "Lily",
        Savannah: "Savannah",
        Hana: "Hana",
        Neha: "Neha",
        Cole: "Cole",
        Harry: "Harry",
        Paige: "Paige",
        Spencer: "Spencer",
    } as const;
}
