/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The voices provided by Vapi
 */
export type FallbackVapiVoiceVoiceId = "Jordan" | "Adi" | "Julia" | "Maibri (Web)" | "Maibri (Phone)" | "Ashley";

export const FallbackVapiVoiceVoiceId = {
    Jordan: "Jordan",
    Adi: "Adi",
    Julia: "Julia",
    MaibriWeb: "Maibri (Web)",
    MaibriPhone: "Maibri (Phone)",
    Ashley: "Ashley",
} as const;
