/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface File_ {
    object?: "file";
    status?: File_.Status;
    /** This is the name of the file. This is just for your own reference. */
    name?: string;
    originalName?: string;
    bytes?: number;
    purpose?: string;
    mimetype?: string;
    key?: string;
    path?: string;
    bucket?: string;
    url?: string;
    parsedTextUrl?: string;
    parsedTextBytes?: number;
    metadata?: Record<string, unknown>;
    /** This is the unique identifier for the file. */
    id: string;
    /** This is the unique identifier for the org that this file belongs to. */
    orgId: string;
    /** This is the ISO 8601 date-time string of when the file was created. */
    createdAt: string;
    /** This is the ISO 8601 date-time string of when the file was last updated. */
    updatedAt: string;
}

export namespace File_ {
    export type Status = "processing" | "done" | "failed";
    export const Status = {
        Processing: "processing",
        Done: "done",
        Failed: "failed",
    } as const;
}
