/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type FormatPlanReplacementsItem = Vapi.FormatPlanReplacementsItem.Exact | Vapi.FormatPlanReplacementsItem.Regex;

export declare namespace FormatPlanReplacementsItem {
    interface Exact extends Vapi.ExactReplacement {
        type: "exact";
    }

    interface Regex extends Vapi.RegexReplacement {
        type: "regex";
    }
}
