/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GeminiMultimodalLivePrebuiltVoiceConfig {
    voiceName: GeminiMultimodalLivePrebuiltVoiceConfig.VoiceName;
}

export namespace GeminiMultimodalLivePrebuiltVoiceConfig {
    export type VoiceName = "Puck" | "Charon" | "Kore" | "Fenrir" | "Aoede";
    export const VoiceName = {
        Puck: "Puck",
        Charon: "Charon",
        Kore: "Kore",
        Fenrir: "Fenrir",
        Aoede: "Aoede",
    } as const;
}
