/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface GhlToolProviderDetails {
    /** This is the Template URL or the Snapshot URL corresponding to the Template. */
    templateUrl?: string;
    setupInstructions?: Vapi.ToolTemplateSetup[];
    workflowId?: string;
    workflowName?: string;
    webhookHookId?: string;
    webhookHookName?: string;
    locationId?: string;
}
