/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GladiaTranscriberModel = "fast" | "accurate" | "solaria-1";
export const GladiaTranscriberModel = {
    Fast: "fast",
    Accurate: "accurate",
    Solaria1: "solaria-1",
} as const;
