/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the Google model that will be used.
 */
export type GoogleModelModel =
    | "gemini-1.5-flash"
    | "gemini-1.5-flash-002"
    | "gemini-1.5-pro"
    | "gemini-1.5-pro-002"
    | "gemini-1.0-pro";

export const GoogleModelModel = {
    Gemini15Flash: "gemini-1.5-flash",
    Gemini15Flash002: "gemini-1.5-flash-002",
    Gemini15Pro: "gemini-1.5-pro",
    Gemini15Pro002: "gemini-1.5-pro-002",
    Gemini10Pro: "gemini-1.0-pro",
} as const;
