/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type GroqModelToolsItem =
    | Vapi.GroqModelToolsItem.Dtmf
    | Vapi.GroqModelToolsItem.EndCall
    | Vapi.GroqModelToolsItem.Voicemail
    | Vapi.GroqModelToolsItem.Function
    | Vapi.GroqModelToolsItem.Ghl
    | Vapi.GroqModelToolsItem.Make
    | Vapi.GroqModelToolsItem.TransferCall;

export declare namespace GroqModelToolsItem {
    interface Dtmf extends Vapi.CreateDtmfToolDto {
        type: "dtmf";
    }

    interface EndCall extends Vapi.CreateEndCallToolDto {
        type: "endCall";
    }

    interface Voicemail extends Vapi.CreateVoicemailToolDto {
        type: "voicemail";
    }

    interface Function extends Vapi.CreateFunctionToolDto {
        type: "function";
    }

    interface Ghl extends Vapi.CreateGhlToolDto {
        type: "ghl";
    }

    interface Make extends Vapi.CreateMakeToolDto {
        type: "make";
    }

    interface TransferCall extends Vapi.CreateTransferCallToolDto {
        type: "transferCall";
    }
}
