/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface HipaaBuyDto {
    /** This is the name of the recipient. */
    recipientName: string;
    /** This is the name of the recipient organization. */
    recipientOrganization: string;
}
