/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type InflectionAiModelToolsItem =
    | Vapi.CreateApiRequestToolDto
    | Vapi.CreateBashToolDto
    | Vapi.CreateComputerToolDto
    | Vapi.CreateDtmfToolDto
    | Vapi.CreateEndCallToolDto
    | Vapi.CreateFunctionToolDto
    | Vapi.CreateGoHighLevelCalendarAvailabilityToolDto
    | Vapi.CreateGoHighLevelCalendarEventCreateToolDto
    | Vapi.CreateGoHighLevelContactCreateToolDto
    | Vapi.CreateGoHighLevelContactGetToolDto
    | Vapi.CreateGoogleCalendarCheckAvailabilityToolDto
    | Vapi.CreateGoogleCalendarCreateEventToolDto
    | Vapi.CreateGoogleSheetsRowAppendToolDto
    | Vapi.CreateMcpToolDto
    | Vapi.CreateQueryToolDto
    | Vapi.CreateSlackSendMessageToolDto
    | Vapi.CreateSmsToolDto
    | Vapi.CreateTextEditorToolDto
    | Vapi.CreateTransferCallToolDto;
