/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InviteUserDto {
    emails: string[];
    role: InviteUserDto.Role;
    redirectTo?: string;
}

export namespace InviteUserDto {
    export type Role = "admin" | "editor" | "viewer";
    export const Role = {
        Admin: "admin",
        Editor: "editor",
        Viewer: "viewer",
    } as const;
}
