/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OAuth2AuthenticationPlanType = "oauth2" | "aws-sts";
export const OAuth2AuthenticationPlanType = {
    Oauth2: "oauth2",
    AwsSts: "aws-sts",
} as const;
