/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface OpenAiResponsesRequest {
    /** This is the assistant that will be used for the chat. To use an existing assistant, use `assistantId` instead. */
    assistantId?: string;
    /** This is the assistant that will be used for the chat. To use an existing assistant, use `assistantId` instead. */
    assistant?: Vapi.CreateAssistantDto;
    /** This is the name of the chat. This is just for your own reference. */
    name?: string;
    /**
     * This is the ID of the session that will be used for the chat.
     * Mutually exclusive with previousChatId.
     */
    sessionId?: string;
    /** Chat input as a string or an array of messages. When using message array, each message requires a role and content. */
    input: Vapi.OpenAiResponsesRequestInput;
    /** Whether to stream the response or not. */
    stream?: boolean;
    /**
     * This is the ID of the chat that will be used as context for the new chat.
     * The messages from the previous chat will be used as context.
     * Mutually exclusive with sessionId.
     */
    previousChatId?: string;
}
