/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the provider-specific ID that will be used.
 */
export type OpenAiVoiceVoiceId = "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer";

export const OpenAiVoiceVoiceId = {
    Alloy: "alloy",
    Echo: "echo",
    Fable: "fable",
    Onyx: "onyx",
    Nova: "nova",
    Shimmer: "shimmer",
} as const;
