/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OpenAiMessage {
    content?: string | null;
    role: OpenAiMessage.Role;
}

export namespace OpenAiMessage {
    export type Role = "assistant" | "function" | "user" | "system" | "tool";
    export const Role = {
        Assistant: "assistant",
        Function: "function",
        User: "user",
        System: "system",
        Tool: "tool",
    } as const;
}
