/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface PhoneNumberHookCallRinging {
    /** This is the event to trigger the hook on */
    on: "call.ringing";
    /** This is the set of actions to perform when the hook triggers */
    do: PhoneNumberHookCallRinging.Do.Item[];
}

export namespace PhoneNumberHookCallRinging {
    export type Do = Do.Item[];

    export namespace Do {
        export type Item = Vapi.TransferPhoneNumberHookAction | Vapi.SayPhoneNumberHookAction;
    }
}
