/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the provider-specific ID that will be used.
 */
export type PlayHtVoiceVoiceId =
    | "jennifer"
    | "melissa"
    | "will"
    | "chris"
    | "matt"
    | "jack"
    | "ruby"
    | "davis"
    | "donna"
    | "michael"
    | string;
