/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RegexOption {
    /**
     * This is the type of the regex option. Options are:
     * - `ignore-case`: Ignores the case of the text being matched. Add
     * - `whole-word`: Matches whole words only.
     * - `multi-line`: Matches across multiple lines.
     */
    type: RegexOption.Type;
    /**
     * This is whether to enable the option.
     *
     * @default false
     */
    enabled: boolean;
}

export namespace RegexOption {
    /**
     * This is the type of the regex option. Options are:
     * - `ignore-case`: Ignores the case of the text being matched. Add
     * - `whole-word`: Matches whole words only.
     * - `multi-line`: Matches across multiple lines.
     */
    export type Type = "ignore-case" | "whole-word" | "multi-line";
    export const Type = {
        IgnoreCase: "ignore-case",
        WholeWord: "whole-word",
        MultiLine: "multi-line",
    } as const;
}
