/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ResponseCompletedEvent {
    /** The completed response */
    response: Vapi.ResponseObject;
    /** Event type */
    type: "response.completed";
}
