/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the response
 */
export type ResponseObjectStatus = "completed" | "failed" | "in_progress" | "incomplete";
export const ResponseObjectStatus = {
    Completed: "completed",
    Failed: "failed",
    InProgress: "in_progress",
    Incomplete: "incomplete",
} as const;
