/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ResponseOutputMessage {
    /** The unique ID of the output message */
    id: string;
    /** Content of the output message */
    content: Vapi.ResponseOutputText[];
    /** The role of the output message */
    role: "assistant";
    /** The status of the message */
    status: Vapi.ResponseOutputMessageStatus;
    /** The type of the output message */
    type: "message";
}
