/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ResponseObject {
    /** Unique identifier for this Response */
    id: string;
    /** The object type */
    object: "response";
    /** Unix timestamp (in seconds) of when this Response was created */
    created_at: number;
    /** Status of the response */
    status: Vapi.ResponseObjectStatus;
    /** Error message if the response failed */
    error?: string | null;
    /** Output messages from the model */
    output: Vapi.ResponseOutputMessage[];
}
