/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the message
 */
export type ResponseOutputMessageStatus = "in_progress" | "completed" | "incomplete";
export const ResponseOutputMessageStatus = {
    InProgress: "in_progress",
    Completed: "completed",
    Incomplete: "incomplete",
} as const;
