/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ServerMessageConversationUpdate {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: Vapi.ServerMessageConversationUpdatePhoneNumber;
    /** This is the type of the message. "conversation-update" is sent when an update is committed to the conversation history. */
    type: "conversation-update";
    /** This is the most up-to-date conversation history at the time the message is sent. */
    messages?: Vapi.ServerMessageConversationUpdateMessagesItem[];
    /** This is the most up-to-date conversation history at the time the message is sent, formatted for OpenAI. */
    messagesOpenAIFormatted: Vapi.OpenAiMessage[];
    /** This is the timestamp of the message. */
    timestamp?: number;
    /**
     * This is a live version of the `call.artifact`.
     *
     * This matches what is stored on `call.artifact` after the call.
     */
    artifact?: Vapi.Artifact;
    /** This is the assistant that the message is associated with. */
    assistant?: Vapi.CreateAssistantDto;
    /** This is the customer that the message is associated with. */
    customer?: Vapi.CreateCustomerDto;
    /** This is the call that the message is associated with. */
    call?: Vapi.Call;
}
