/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the destination to forward the call to if the request is "forward".
 */
export type ServerMessagePhoneCallControlDestination =
    | Vapi.ServerMessagePhoneCallControlDestination.Number
    | Vapi.ServerMessagePhoneCallControlDestination.Sip;

export declare namespace ServerMessagePhoneCallControlDestination {
    interface Number extends Vapi.TransferDestinationNumber {
        type: "number";
    }

    interface Sip extends Vapi.TransferDestinationSip {
        type: "sip";
    }
}
