/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the message that will be spoken to the user as the tool is running.
 */
export type ServerMessageResponseTransferDestinationRequestMessage =
    | Vapi.ToolMessageStart
    | Vapi.ToolMessageComplete
    | Vapi.ToolMessageFailed
    | Vapi.ToolMessageDelayed;
