/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface ServerMessageResponseHandoffDestinationRequest {
    /** This is the destination you'd like the call to be transferred to. */
    destination: Vapi.HandoffDestinationAssistant;
}
