/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SupabaseBucketPlan {
    /**
     * This is the S3 Region. It should look like us-east-1
     * It should be one of the supabase regions defined in the SUPABASE_REGION enum
     * Check https://supabase.com/docs/guides/platform/regions for up to date regions
     */
    region: SupabaseBucketPlan.Region;
    /**
     * This is the S3 compatible URL for Supabase S3
     * This should look like https://<project-ID>.supabase.co/storage/v1/s3
     */
    url: string;
    /**
     * This is the Supabase S3 Access Key ID.
     * The user creates this in the Supabase project Storage settings
     */
    accessKeyId: string;
    /**
     * This is the Supabase S3 Secret Access Key.
     * The user creates this in the Supabase project Storage settings along with the access key id
     */
    secretAccessKey: string;
    /**
     * This is the Supabase S3 Bucket Name.
     * The user must create this in Supabase under Storage > Buckets
     * A bucket that does not exist will not be checked now, but file uploads will fail
     */
    name: string;
    /**
     * This is the Supabase S3 Bucket Folder Path.
     * The user can create this in Supabase under Storage > Buckets
     * A path that does not exist will not be checked now, but file uploads will fail
     * A Path is like a folder in the bucket
     * Eg. If the bucket is called "my-bucket" and the path is "my-folder", the full path is "my-bucket/my-folder"
     */
    path?: string;
}

export namespace SupabaseBucketPlan {
    /**
     * This is the S3 Region. It should look like us-east-1
     * It should be one of the supabase regions defined in the SUPABASE_REGION enum
     * Check https://supabase.com/docs/guides/platform/regions for up to date regions
     */
    export type Region =
        | "us-west-1"
        | "us-east-1"
        | "us-east-2"
        | "ca-central-1"
        | "eu-west-1"
        | "eu-west-2"
        | "eu-west-3"
        | "eu-central-1"
        | "eu-central-2"
        | "eu-north-1"
        | "ap-south-1"
        | "ap-southeast-1"
        | "ap-northeast-1"
        | "ap-northeast-2"
        | "ap-southeast-2"
        | "sa-east-1";
    export const Region = {
        UsWest1: "us-west-1",
        UsEast1: "us-east-1",
        UsEast2: "us-east-2",
        CaCentral1: "ca-central-1",
        EuWest1: "eu-west-1",
        EuWest2: "eu-west-2",
        EuWest3: "eu-west-3",
        EuCentral1: "eu-central-1",
        EuCentral2: "eu-central-2",
        EuNorth1: "eu-north-1",
        ApSouth1: "ap-south-1",
        ApSoutheast1: "ap-southeast-1",
        ApNortheast1: "ap-northeast-1",
        ApNortheast2: "ap-northeast-2",
        ApSoutheast2: "ap-southeast-2",
        SaEast1: "sa-east-1",
    } as const;
}
