/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type TemplateProviderDetails =
    | Vapi.TemplateProviderDetails.Make
    | Vapi.TemplateProviderDetails.Ghl
    | Vapi.TemplateProviderDetails.Function;

export declare namespace TemplateProviderDetails {
    interface Make extends Vapi.MakeToolProviderDetails {
        type: "make";
    }

    interface Ghl extends Vapi.GhlToolProviderDetails {
        type: "ghl";
    }

    interface Function extends Vapi.FunctionToolProviderDetails {
        type: "function";
    }
}
