/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface TestSuiteTestsPaginatedResponse {
    /** A list of test suite tests. */
    results: TestSuiteTestsPaginatedResponse.Results.Item[];
    /** Metadata about the pagination. */
    metadata: Vapi.PaginationMeta;
}

export namespace TestSuiteTestsPaginatedResponse {
    export type Results = Results.Item[];

    export namespace Results {
        export type Item = Vapi.TestSuiteTestVoice | Vapi.TestSuiteTestChat;
    }
}
