/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TestSuiteRunScorerAi {
    /** This is the type of the scorer, which must be AI. */
    type: "ai";
    /** This is the result of the test suite. */
    result: TestSuiteRunScorerAi.Result;
    /** This is the reasoning provided by the AI scorer. */
    reasoning: string;
    /** This is the rubric used by the AI scorer. */
    rubric: string;
}

export namespace TestSuiteRunScorerAi {
    /**
     * This is the result of the test suite.
     */
    export type Result = "pass" | "fail";
    export const Result = {
        Pass: "pass",
        Fail: "fail",
    } as const;
}
