/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TimeRange {
    /**
     * This is the time step for aggregations.
     *
     * If not provided, defaults to returning for the entire time range.
     */
    step?: TimeRange.Step;
    /**
     * This is the start date for the time range.
     *
     * If not provided, defaults to the 7 days ago.
     */
    start?: string;
    /**
     * This is the end date for the time range.
     *
     * If not provided, defaults to now.
     */
    end?: string;
    /**
     * This is the timezone you want to set for the query.
     *
     * If not provided, defaults to UTC.
     */
    timezone?: string;
}

export namespace TimeRange {
    /**
     * This is the time step for aggregations.
     *
     * If not provided, defaults to returning for the entire time range.
     */
    export type Step =
        | "second"
        | "minute"
        | "hour"
        | "day"
        | "week"
        | "month"
        | "quarter"
        | "year"
        | "decade"
        | "century"
        | "millennium";
    export const Step = {
        Second: "second",
        Minute: "minute",
        Hour: "hour",
        Day: "day",
        Week: "week",
        Month: "month",
        Quarter: "quarter",
        Year: "year",
        Decade: "decade",
        Century: "century",
        Millennium: "millennium",
    } as const;
}
