/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TransferFallbackPlan {
    /** This is the message the assistant will deliver to the customer if the transfer fails. */
    message: Vapi.TransferFallbackPlanMessage;
    /**
     * This controls what happens after delivering the failure message to the customer.
     * - true: End the call after delivering the failure message (default)
     * - false: Keep the assistant on the call to continue handling the customer's request
     *
     * @default true
     */
    endCallEnabled?: boolean;
}
