/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface UpdateSessionDto {
    /** This is the new name for the session. Maximum length is 40 characters. */
    name?: string;
    /** This is the new status for the session. */
    status?: Vapi.UpdateSessionDtoStatus;
    /** Array of updated chat messages */
    messages?: Vapi.UpdateSessionDtoMessagesItem[];
}
