/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type UpdateToolTemplateDtoProviderDetails =
    | Vapi.MakeToolProviderDetails
    | Vapi.GhlToolProviderDetails
    | Vapi.FunctionToolProviderDetails
    | Vapi.GoogleCalendarCreateEventToolProviderDetails
    | Vapi.GoogleSheetsRowAppendToolProviderDetails
    | Vapi.GoHighLevelCalendarAvailabilityToolProviderDetails
    | Vapi.GoHighLevelCalendarEventCreateToolProviderDetails
    | Vapi.GoHighLevelContactCreateToolProviderDetails
    | Vapi.GoHighLevelContactGetToolProviderDetails;
