/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type UpdateTransferCallToolDtoDestinationsItem =
    | Vapi.TransferDestinationAssistant
    | Vapi.TransferDestinationNumber
    | Vapi.TransferDestinationSip;
