/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type VapiModelStepsItem = Vapi.VapiModelStepsItem.Handoff | Vapi.VapiModelStepsItem.Callback;

export declare namespace VapiModelStepsItem {
    interface Handoff extends Vapi.HandoffStep {
        type: "handoff";
    }

    interface Callback extends Vapi.CallbackStep {
        type: "callback";
    }
}
