/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VapiSmartEndpointingPlan {
    /** This is the provider for the smart endpointing plan. */
    provider: VapiSmartEndpointingPlan.Provider;
}

export namespace VapiSmartEndpointingPlan {
    /**
     * This is the provider for the smart endpointing plan.
     */
    export type Provider = "vapi" | "livekit" | "custom-endpointing-model";
    export const Provider = {
        Vapi: "vapi",
        Livekit: "livekit",
        CustomEndpointingModel: "custom-endpointing-model",
    } as const;
}
