/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the type of output you'd like.
 *
 * `string`, `number`, `boolean` are primitive types.
 */
export type VariableExtractionSchemaType = "string" | "number" | "integer" | "boolean";
export const VariableExtractionSchemaType = {
    String: "string",
    Number: "number",
    Integer: "integer",
    Boolean: "boolean",
} as const;
