/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

export interface WebChat {
    /** This is the unique identifier for the chat. */
    id: string;
    /** This is the ID of the session for the chat. Send it in the next chat request to continue the conversation. */
    sessionId?: string;
    /** This is the output messages generated by the system in response to the input. */
    output: WebChat.Output.Item[];
}

export namespace WebChat {
    export type Output = Output.Item[];

    export namespace Output {
        export type Item =
            | Vapi.SystemMessage
            | Vapi.UserMessage
            | Vapi.AssistantMessage
            | Vapi.ToolMessage
            | Vapi.DeveloperMessage;
    }
}
