/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface WorkflowAnthropicModel {
    /** This is the specific Anthropic/Claude model that will be used. */
    model: Vapi.WorkflowAnthropicModelModel;
    /** This is the provider of the model. Ex. anthropic */
    provider: "anthropic";
    /**
     * This is the optional configuration for Anthropic's thinking feature.
     * Only applicable for claude-3-7-sonnet-20250219 model.
     * If provided, maxTokens must be greater than thinking.budgetTokens.
     */
    thinking?: Vapi.AnthropicThinkingConfig;
    /** This is the temperature of the model. */
    temperature?: number;
    /** This is the max tokens of the model. */
    maxTokens?: number;
}
