/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * These are the options for the workflow's LLM.
 */
export type WorkflowUserEditableModel = Vapi.WorkflowOpenAiModel | Vapi.WorkflowAnthropicModel;
