/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type WorkflowBlockMessagesItem =
    | Vapi.WorkflowBlockMessagesItem.BlockStart
    | Vapi.WorkflowBlockMessagesItem.BlockComplete;

export declare namespace WorkflowBlockMessagesItem {
    interface BlockStart extends Vapi.BlockStartMessage {
        type: "block-start";
    }

    interface BlockComplete extends Vapi.BlockCompleteMessage {
        type: "block-complete";
    }
}
