/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface WorkflowGoogleModel {
    /** This is the provider of the model (`google`). */
    provider: "google";
    /** This is the name of the model. Ex. cognitivecomputations/dolphin-mixtral-8x7b */
    model: Vapi.WorkflowGoogleModelModel;
    /** This is the temperature of the model. */
    temperature?: number;
    /** This is the max tokens of the model. */
    maxTokens?: number;
}
