/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type ToolsGetResponse =
    | Vapi.ToolsGetResponse.Dtmf
    | Vapi.ToolsGetResponse.EndCall
    | Vapi.ToolsGetResponse.Function
    | Vapi.ToolsGetResponse.Ghl
    | Vapi.ToolsGetResponse.Make
    | Vapi.ToolsGetResponse.TransferCall
    | Vapi.ToolsGetResponse.Output;

export declare namespace ToolsGetResponse {
    interface Dtmf extends Vapi.DtmfTool {
        type: "dtmf";
    }

    interface EndCall extends Vapi.EndCallTool {
        type: "endCall";
    }

    interface Function extends Vapi.FunctionTool {
        type: "function";
    }

    interface Ghl extends Vapi.GhlTool {
        type: "ghl";
    }

    interface Make extends Vapi.MakeTool {
        type: "make";
    }

    interface TransferCall extends Vapi.TransferCallTool {
        type: "transferCall";
    }

    interface Output extends Vapi.OutputTool {
        type: "output";
    }
}
