/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type ToolsUpdateResponse =
    | Vapi.ToolsUpdateResponse.Dtmf
    | Vapi.ToolsUpdateResponse.EndCall
    | Vapi.ToolsUpdateResponse.Function
    | Vapi.ToolsUpdateResponse.Ghl
    | Vapi.ToolsUpdateResponse.Make
    | Vapi.ToolsUpdateResponse.TransferCall
    | Vapi.ToolsUpdateResponse.Output;

export declare namespace ToolsUpdateResponse {
    interface Dtmf extends Vapi.DtmfTool {
        type: "dtmf";
    }

    interface EndCall extends Vapi.EndCallTool {
        type: "endCall";
    }

    interface Function extends Vapi.FunctionTool {
        type: "function";
    }

    interface Ghl extends Vapi.GhlTool {
        type: "ghl";
    }

    interface Make extends Vapi.MakeTool {
        type: "make";
    }

    interface TransferCall extends Vapi.TransferCallTool {
        type: "transferCall";
    }

    interface Output extends Vapi.OutputTool {
        type: "output";
    }
}
