/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type OpenAiResponsesRequestInputItem =
    | Vapi.SystemMessage
    | Vapi.UserMessage
    | Vapi.AssistantMessage
    | Vapi.ToolMessage
    | Vapi.DeveloperMessage;
