/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder = "ASC" | "DESC";
export const ProviderResourceControllerGetProviderResourcesPaginatedRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
