/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateWorkflowDto {
    nodes?: Vapi.UpdateWorkflowDtoNodesItem[];
    /**
     * This is the transcriber for the workflow.
     *
     * This can be overridden at node level using `nodes[n].transcriber`.
     */
    transcriber?: Vapi.UpdateWorkflowDtoTranscriber;
    /**
     * This is the voice for the workflow.
     *
     * This can be overridden at node level using `nodes[n].voice`.
     */
    voice?: Vapi.UpdateWorkflowDtoVoice;
    /**
     * This is the plan for observability of workflow's calls.
     *
     * Currently, only Langfuse is supported.
     */
    observabilityPlan?: Vapi.LangfuseObservabilityPlan;
    /** These are dynamic credentials that will be used for the workflow calls. By default, all the credentials are available for use in the call but you can supplement an additional credentials using this. Dynamic credentials override existing credentials. */
    credentials?: Vapi.UpdateWorkflowDtoCredentialsItem[];
    name?: string;
    edges?: Vapi.Edge[];
    globalPrompt?: string;
    /**
     * This is where Vapi will send webhooks. You can find all webhooks available along with their shape in ServerMessage schema.
     *
     * The order of precedence is:
     *
     * 1. tool.server
     * 2. workflow.server / assistant.server
     * 3. phoneNumber.server
     * 4. org.server
     */
    server?: Vapi.Server;
    /** This is the compliance plan for the workflow. It allows you to configure HIPAA and other compliance settings. */
    compliancePlan?: Vapi.CompliancePlan;
    /** This is the plan for analysis of workflow's calls. Stored in `call.analysis`. */
    analysisPlan?: Vapi.AnalysisPlan;
    /** This is the plan for artifacts generated during workflow's calls. Stored in `call.artifact`. */
    artifactPlan?: Vapi.ArtifactPlan;
    /**
     * This is the plan for when the workflow nodes should start talking.
     *
     * You should configure this if you're running into these issues:
     * - The assistant is too slow to start talking after the customer is done speaking.
     * - The assistant is too fast to start talking after the customer is done speaking.
     * - The assistant is so fast that it's actually interrupting the customer.
     */
    startSpeakingPlan?: Vapi.StartSpeakingPlan;
    /**
     * This is the plan for when workflow nodes should stop talking on customer interruption.
     *
     * You should configure this if you're running into these issues:
     * - The assistant is too slow to recognize customer's interruption.
     * - The assistant is too fast to recognize customer's interruption.
     * - The assistant is getting interrupted by phrases that are just acknowledgments.
     * - The assistant is getting interrupted by background noises.
     * - The assistant is not properly stopping -- it starts talking right after getting interrupted.
     */
    stopSpeakingPlan?: Vapi.StopSpeakingPlan;
    /**
     * This is the plan for real-time monitoring of the workflow's calls.
     *
     * Usage:
     * - To enable live listening of the workflow's calls, set `monitorPlan.listenEnabled` to `true`.
     * - To enable live control of the workflow's calls, set `monitorPlan.controlEnabled` to `true`.
     */
    monitorPlan?: Vapi.MonitorPlan;
    /**
     * This enables filtering of noise and background speech while the user is talking.
     *
     * Features:
     * - Smart denoising using Krisp
     * - Fourier denoising
     *
     * Both can be used together. Order of precedence:
     * - Smart denoising
     * - Fourier denoising
     */
    backgroundSpeechDenoisingPlan?: Vapi.BackgroundSpeechDenoisingPlan;
    /** These are the credentials that will be used for the workflow calls. By default, all the credentials are available for use in the call but you can provide a subset using this. */
    credentialIds?: string[];
}
