/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type PhoneNumbersCreateRequest =
    | Vapi.PhoneNumbersCreateRequest.ByoPhoneNumber
    | Vapi.PhoneNumbersCreateRequest.Twilio
    | Vapi.PhoneNumbersCreateRequest.Vonage
    | Vapi.PhoneNumbersCreateRequest.Vapi;

export declare namespace PhoneNumbersCreateRequest {
    interface ByoPhoneNumber extends Vapi.CreateByoPhoneNumberDto {
        provider: "byo-phone-number";
    }

    interface Twilio extends Vapi.CreateTwilioPhoneNumberDto {
        provider: "twilio";
    }

    interface Vonage extends Vapi.CreateVonagePhoneNumberDto {
        provider: "vonage";
    }

    interface Vapi extends Vapi.CreateVapiPhoneNumberDto {
        provider: "vapi";
    }
}
