/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type PhoneNumbersGetResponse =
    | Vapi.PhoneNumbersGetResponse.ByoPhoneNumber
    | Vapi.PhoneNumbersGetResponse.Twilio
    | Vapi.PhoneNumbersGetResponse.Vonage
    | Vapi.PhoneNumbersGetResponse.Vapi;

export declare namespace PhoneNumbersGetResponse {
    interface ByoPhoneNumber extends Vapi.ByoPhoneNumber {
        provider: "byo-phone-number";
    }

    interface Twilio extends Vapi.TwilioPhoneNumber {
        provider: "twilio";
    }

    interface Vonage extends Vapi.VonagePhoneNumber {
        provider: "vonage";
    }

    interface Vapi extends Vapi.VapiPhoneNumber {
        provider: "vapi";
    }
}
