/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LoggingControllerLogsDeleteQueryRequest {
    /**
     * This is the unique identifier for the org that this log belongs to.
     */
    orgId?: string;
    /**
     * This is the ID of the assistant.
     */
    assistantId?: string;
    /**
     * This is the ID of the phone number.
     */
    phoneNumberId?: string;
    /**
     * This is the ID of the customer.
     */
    customerId?: string;
    /**
     * This is the ID of the squad.
     */
    squadId?: string;
    /**
     * This is the ID of the call.
     */
    callId?: string;
}
