/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../../index";

/**
 * @example
 *     {
 *         category: "bug-report",
 *         subject: "subject",
 *         message: "message"
 *     }
 */
export interface CreateSupportTicketDto {
    /** The category of the support request */
    category: Vapi.CreateSupportTicketDtoCategory;
    /** The subcategory for bug reports */
    bugSubcategory?: Vapi.CreateSupportTicketDtoBugSubcategory;
    /** The subject/title of the support request */
    subject: string;
    /** Detailed description of the issue or request */
    message: string;
    /** Call IDs and recording URLs if applicable */
    callDetails?: string;
}
